### ISSUE TITLE
java -Xint lanuch NPE at java.util.HashMap.putVal(HashMap.java:631)

### ISSUE THREAD

**Issue by pengying-flora** [sendaoYan/riscv-port-jdk8u-ysd#266]
```
> riscv-jdk8u-1027-1746-slowdebug-binary/bin/java -Xmx10m -Xms10m -XX:ParallelGCThreads=1 -version 
Error occurred during initialization of VM
java.lang.ExceptionInInitializerError
        at sun.misc.Unsafe.<clinit>(Unsafe.java:49)
        at sun.misc.SharedSecrets.<clinit>(SharedSecrets.java:48)
        at java.lang.ref.Reference.<clinit>(Reference.java:235)
Caused by: java.lang.NullPointerException
        at java.util.HashMap.putVal(HashMap.java:631)
        at java.util.HashMap.put(HashMap.java:613)
        at sun.reflect.Reflection.<clinit>(Reflection.java:46)
        at sun.misc.Unsafe.<clinit>(Unsafe.java:49)
        at sun.misc.SharedSecrets.<clinit>(SharedSecrets.java:48)
        at java.lang.ref.Reference.<clinit>(Reference.java:235)
```
[jdk8u-riscv64-bytecodes.log](https://github.com/user-attachments/files/17540034/jdk8u-riscv64-bytecodes.log)
[jdk8u-VerifyOops.log](https://github.com/user-attachments/files/17540035/jdk8u-VerifyOops.log)
[265-fixed.zip](https://github.com/user-attachments/files/17540036/265-fixed.zip)
[jdk8u-riscv64-bytecodes.log](https://github.com/user-attachments/files/17540046/jdk8u-riscv64-bytecodes.log)
[jdk8u-VerifyOops.log](https://github.com/user-attachments/files/17540047/jdk8u-VerifyOops.log)
[jdk8u-aarch64-bytecodes.log](https://github.com/user-attachments/files/17540049/jdk8u-aarch64-bytecodes.log)
[jdk8u-riscv64.log](https://github.com/user-attachments/files/17540056/jdk8u-riscv64.log)

**Comment by sendaoYan** [comment]
[266.patch](https://github.com/user-attachments/files/17553603/266.patch)

**Comment by sendaoYan** [comment]
To github.com:sendaoYan/riscv-port-jdk8u-ysd.git
   686a7c69b2e..cb181399c89  minus-jbs8276799 -> minus-jbs8276799

**Comment by pengying-flora** [comment]
[before.zip](https://github.com/user-attachments/files/17553728/before.zip)
[make-inc-gcc9-cross-riscv64-release.log](https://github.com/user-attachments/files/17553730/make-inc-gcc9-cross-riscv64-release.log)
[make-inc-gcc9-cross-riscv64-slowdebug.log](https://github.com/user-attachments/files/17553731/make-inc-gcc9-cross-riscv64-slowdebug.log)
[jdk8u-riscv64.log](https://github.com/user-attachments/files/17553732/jdk8u-riscv64.log)
[make-inc-gcc9-cross-riscv64-fastdebug.log](https://github.com/user-attachments/files/17553733/make-inc-gcc9-cross-riscv64-fastdebug.log)

**Comment by pengying-flora** [comment]
[after.zip](https://github.com/user-attachments/files/17553943/after.zip)
