### ISSUE TITLE
java lanuch error java.lang.IllegalArgumentException: Null charset name at java.nio.charset.Charset.lookup(Charset.java:457)

### ISSUE THREAD

**Issue by sendaoYan** [sendaoYan/riscv-port-jdk8u-ysd#267]
```
> ./riscv-jdk8u-1029-1553-slowdebug-binary/bin/java -version
Error occurred during initialization of VM
java.lang.IllegalArgumentException: Null charset name
        at java.nio.charset.Charset.lookup(Charset.java:457)
        at java.nio.charset.Charset.defaultCharset(Charset.java:609)
        at sun.nio.cs.StreamEncoder.forOutputStreamWriter(StreamEncoder.java:56)
        at java.io.OutputStreamWriter.<init>(OutputStreamWriter.java:111)
        at java.io.PrintStream.<init>(PrintStream.java:104)
        at java.io.PrintStream.<init>(PrintStream.java:151)
        at java.lang.System.newPrintStream(System.java:1162)
        at java.lang.System.initializeSystemClass(System.java:1207)
```

**Comment by pengying-flora** [comment]
[before.zip](https://github.com/user-attachments/files/17553986/before.zip)
[jdk8u-riscv64.log](https://github.com/user-attachments/files/17553987/jdk8u-riscv64.log)
[after.zip](https://github.com/user-attachments/files/17553989/after.zip)

**Comment by sendaoYan** [comment]
```shell
time ./riscv-jdk8u-1029-1553-slowdebug-binary/bin/java -Xms10M -Xmx10M -XX:ParallelGCThreads=1 -XX:+CIObjectFactoryVerify -XX:+CMSVerifyReturnedBytes -XX:+ExitVMOnVerifyError -XX:+FLSVerifyAllHeapReferences -XX:+FLSVerifyDictionary -XX:+FLSVerifyIndexTable -XX:+FLSVerifyLists -XX:+G1HRRSFlushLogBuffersOnVerify -XX:+G1VerifyBitmaps -XX:+G1VerifyCTCleanup -XX:+G1VerifyDuringGCPrintReachable -XX:+G1VerifyHeapRegionCodeRoots -XX:+G1VerifyRSetsDuringFullGC -XX:+VerifyActivationFrameSize -XX:+VerifyAdapterSharing -XX:+VerifyAfterGC -XX:+VerifyAliases -XX:+VerifyBeforeGC -XX:+VerifyBeforeIteration -XX:+VerifyBlockOffsetArray -XX:+VerifyCodeCacheOften -XX:+VerifyCompiledCode -XX:+VerifyDuringGC -XX:+VerifyDuringStartup -XX:+VerifyFPU -XX:+VerifyGenericSignatures -XX:+VerifyGraphEdges -XX:+VerifyIdealNodeCount -XX:+VerifyIterativeGVN -XX:+VerifyJNIEnvThread -XX:+VerifyLastFrame -XX:+VerifyLoopOptimizations -XX:+VerifyOops -XX:+VerifyOpto -XX:+VerifyOptoOopOffsets -XX:+VerifyReflectionBytecodes -XX:+VerifyRegisterAllocator -XX:+VerifyRememberedSets -XX:+VerifySharedSpaces -XX:+VerifyStack -XX:+VerifyStackAtCalls -XX:+VerifyStringTableAtExit -XX:+VerifyThread -version
```
